%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

%global __cmake_in_source_build 1

Name:           ros-humble-autoware-component-interface-specs
Version:        1.7.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS autoware_component_interface_specs package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-autoware-adapi-v1-msgs
Requires:       ros-humble-autoware-control-msgs
Requires:       ros-humble-autoware-localization-msgs
Requires:       ros-humble-autoware-map-msgs
Requires:       ros-humble-autoware-perception-msgs
Requires:       ros-humble-autoware-planning-msgs
Requires:       ros-humble-autoware-system-msgs
Requires:       ros-humble-autoware-vehicle-msgs
Requires:       ros-humble-nav-msgs
Requires:       ros-humble-rcl
Requires:       ros-humble-rclcpp
Requires:       ros-humble-rosidl-runtime-cpp
Requires:       ros-humble-sensor-msgs
Requires:       ros-humble-ros-workspace
BuildRequires:  ros-humble-ament-cmake-auto
BuildRequires:  ros-humble-autoware-adapi-v1-msgs
BuildRequires:  ros-humble-autoware-cmake
BuildRequires:  ros-humble-autoware-control-msgs
BuildRequires:  ros-humble-autoware-localization-msgs
BuildRequires:  ros-humble-autoware-map-msgs
BuildRequires:  ros-humble-autoware-perception-msgs
BuildRequires:  ros-humble-autoware-planning-msgs
BuildRequires:  ros-humble-autoware-system-msgs
BuildRequires:  ros-humble-autoware-vehicle-msgs
BuildRequires:  ros-humble-nav-msgs
BuildRequires:  ros-humble-rcl
BuildRequires:  ros-humble-rclcpp
BuildRequires:  ros-humble-rosidl-runtime-cpp
BuildRequires:  ros-humble-sensor-msgs
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-humble-ament-cmake-gtest
BuildRequires:  ros-humble-ament-lint-auto
BuildRequires:  ros-humble-autoware-lint-common
%endif

%description
The autoware_component_interface_specs package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Tue Feb 17 2026 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.7.0-1
- Autogenerated by Bloom

* Tue Aug 12 2025 Takagi, Isamu <isamu.takagi@tier4.jp> - 1.4.0-1
- Autogenerated by Bloom

